# Generated by Django 4.1.4 on 2022-12-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='store/data')),
                ('desc', models.TextField(default='', max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('meta_title', models.CharField(default='', max_length=150)),
                ('meta_keywords', models.CharField(default='', max_length=150)),
                ('meta_desc', models.TextField(default='', max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('p_img', models.ImageField(upload_to='store/data')),
                ('s_desc', models.CharField(default='', max_length=120)),
                ('desc', models.TextField(default='', max_length=500)),
                ('quntity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default,1=Hidden')),
                ('tag', models.CharField(max_length=50)),
                ('meta_title', models.CharField(default='', max_length=150)),
                ('meta_keywords', models.CharField(default='', max_length=150)),
                ('meta_desc', models.TextField(default='', max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
